### ISSUE TITLE
Redesign the layout for a particular address/verified entry

### ISSUE THREAD

**Issue by asood123** [Uniswap/sybil-interface#16]
There's some confusion right now around where the link should go. Ideally, we need to show following info:
- wallet address
- identity (twitter or ENS or github or something else down the line)

There can be up to 3 outgoing links:
- sybil.org's detail page for this wallet address
- to their verified profile, like twitter.com/[username]
- to Etherscan

Potentially, a copy button to copy the address would be nice as well.

**Comment by ianlapham** [comment]
Pretty sure this one is solved - always a link to etherscan and if theres twitter that link is there too
